Payment Libraries documentation
nevermined-io/app_docs pull request #147
Opened 2024-10-18 09:39 UTC by aaitor

## Description

Add a description of your changes here.

## Is this PR related with an open issue?

Related to Issue #

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 
## Checklist:

- [ ] Follows the code style of this project.
- [ ] Tests Cover Changes
- [ ] Documentation

2024-10-18 15:12 UTC, metabacalhau requested changes

2024-10-18 15:12 UTC, metabacalhau commented on docs/libraries/06-query-agents.md
> +Nevermined recomends to use the [Nevermined Query Protocol](https://docs.nevermined.io/docs/protocol/query-protocol) but doesn't enforce it.
```suggestion
Nevermined recommends to use the [Nevermined Query Protocol](https://docs.nevermined.io/docs/protocol/query-protocol) but doesn't enforce it. 
```

2024-10-18 15:12 UTC, metabacalhau commented on docs/libraries/06-query-agents.md
> +The [Nevermined Query Protocol](https://docs.nevermined.io/docs/protocol/query-protocol) standarizes the interface of AI Agents and Services. This means that if an AI Agent implements this protocol,
```suggestion
The [Nevermined Query Protocol](https://docs.nevermined.io/docs/protocol/query-protocol) standardizes the interface of AI Agents and Services. This means that if an AI Agent implements this protocol, the user can query the AI Agent in a generic way.
```

2024-10-18 15:18 UTC, eruizgar91 approved these changes

2024-10-20 06:38 UTC, metabacalhau approved these changes

2024-10-21 09:59 UTC, merged